---
title: "stat297hw2"
author: "Dylan Shoemaker, Aaron Wilhelm"
date: "October 16, 2017"
output: html_document
---

```{r}
#Fizz Buzz Problem
array = c()

for (i in 1:1000) {
  if (i %% 3 == 0){
    if (i %% 5 == 0){
      q = "Fizz Buzz"
      array[i] <- q
    }else{
      r = "Fizz"
      array[i] <- r
    }
  }else if (i %% 5 == 0){
    s = "Buzz"
    array[i] <- s
  }else{
    array[i] <- i
  }  
}

print(array)
```

```{r}
#First
library(plot3D)
library(animation)

ani.options(interval=0.5)

saveHTML({
# Number of steps
steps <- 10^4

# Seed Set
set.seed(1982)
Ut <- runif(steps)
head(Ut)


# Direction probability
probs <- c(0.25, 0.5, 0.75)

# Initial matrix
step_direction <- matrix(0, steps+1, 2)

# Start random walk
for (i in seq(2, steps+1)){
  # Draw a random number from U(0,1)
  rn = runif(1)
  
  # Go right if rn \in [0,prob[1])
  if (rn < probs[1]) {step_direction[i,1] = 1}
  
  # Go left if rn \in [probs[1], probs[2])
  if (rn >= probs[1] && rn < probs[2]) {step_direction[i,1] = -1}
  
  # Go forward if rn \in [probs[2], probs[3])
  if (rn >= probs[2] && rn < probs[3]) {step_direction[i,2] = 1}
  
  # Go backward if rn \in [probs[3],1]
  if (rn >= probs[3]) {step_direction[i,2] = -1}
}

# Cumulative steps
position = data.frame(x = cumsum(step_direction[, 1]), 
                      y = cumsum(step_direction[, 2]))

# Graph parameters
color = "blue4"
xlab = "X-position"
ylab = "Y-position"
pt_pch = 16
pt.cex = 2
main = paste("Segment 3D Graph w/", steps, "steps", sep = " ")
hues = seq(15, 375, length = 3)
pt_col = hcl(h = hues, l = 65, c = 100)[1:2]
par(mar = c(5.1, 5.1, 1, 2.1))

# Main plot
plot(NA,  xlim = range(position[,1]), 
     ylim = range(range(position[,2])), 
     xlab = xlab, ylab = ylab, xaxt = 'n', 
     yaxt = 'n', bty = "n", ann = FALSE)
win_dim = par("usr")

par(new = TRUE)
plot(NA, xlim = range(position[,1]), ylim = c(win_dim[3], win_dim[4] + 0.09*(win_dim[4] - win_dim[3])),
     xlab = xlab, ylab = ylab, xaxt = 'n', yaxt = 'n', bty = "n")
win_dim = par("usr")

# Add grid
grid(NULL, NULL, lty = 1, col = "grey95")

# Add title
x_vec = c(win_dim[1], win_dim[2], win_dim[2], win_dim[1])
y_vec = c(win_dim[4], win_dim[4],
          win_dim[4] - 0.09*(win_dim[4] - win_dim[3]),
          win_dim[4] - 0.09*(win_dim[4] - win_dim[3]))
polygon(x_vec, y_vec, col = "grey95", border = NA)
text(x = mean(c(win_dim[1], win_dim[2])), y = (win_dim[4] - 0.09/2*(win_dim[4] - win_dim[3])), main)

# Add axes and box
lines(x_vec[1:2], rep((win_dim[4] - 0.09*(win_dim[4] - win_dim[3])),2), col = 1)
box()
axis(1, padj = 0.3)
y_axis = axis(2, labels = FALSE, tick = FALSE)
y_axis = y_axis[y_axis < (win_dim[4] - 0.09*(win_dim[4] - win_dim[3]))]
axis(2, padj = -0.2, at = y_axis)

# Add trajectory
lines(position, type = "l", col = color, pch = 16)

# Start and end points
points(c(0,position[steps+1,1]), c(0,position[steps+1,2]), cex = pt.cex, col = pt_col, pch = pt_pch)

# Legend
leg_pos = c(min(position[,1]), max(position[,2]))
legend(leg_pos[1], leg_pos[2], c("Start","End"), 
       col = pt_col, pch = pt_pch, pt.cex = pt.cex, bty = "n")



#Second
steps <- 10^5
set.seed(2000)
Ut <- runif(steps)
head(Ut)

# Direction probability
probs <- c(0.25, 0.5, 0.75)

# Initial matrix
step_direction <- matrix(0, steps+1, 2)

# Start random walk
for (i in seq(2, steps+1)){
  # Draw a random number from U(0,1)
  rn = runif(1)
  
  # Go right if rn \in [0,prob[1])
  if (rn < probs[1]) {step_direction[i,1] = 1}
  
  # Go left if rn \in [probs[1], probs[2])
  if (rn >= probs[1] && rn < probs[2]) {step_direction[i,1] = -1}
  
  # Go forward if rn \in [probs[2], probs[3])
  if (rn >= probs[2] && rn < probs[3]) {step_direction[i,2] = 1}
  
  # Go backward if rn \in [probs[3],1]
  if (rn >= probs[3]) {step_direction[i,2] = -1}
}

# Cumulative steps
position = data.frame(x = cumsum(step_direction[, 1]), 
                      y = cumsum(step_direction[, 2]))

# Graph parameters
color = "blue4"
xlab = "X-position"
ylab = "Y-position"
pt_pch = 16
pt.cex = 2
main = paste("Segment 3D Graph w/", steps, "steps", sep = " ")
hues = seq(15, 375, length = 3)
pt_col = hcl(h = hues, l = 65, c = 100)[1:2]
par(mar = c(5.1, 5.1, 1, 2.1))

# Main plot
plot(NA,  xlim = range(position[,1]), 
           ylim = range(range(position[,2])), 
           xlab = xlab, ylab = ylab, xaxt = 'n', 
           yaxt = 'n', bty = "n", ann = FALSE)
win_dim = par("usr")

par(new = TRUE)
plot(NA, xlim = range(position[,1]), ylim = c(win_dim[3], win_dim[4] + 0.09*(win_dim[4] - win_dim[3])),
     xlab = xlab, ylab = ylab, xaxt = 'n', yaxt = 'n', bty = "n")
win_dim = par("usr")

# Add grid
grid(NULL, NULL, lty = 1, col = "grey95")

# Add title
x_vec = c(win_dim[1], win_dim[2], win_dim[2], win_dim[1])
y_vec = c(win_dim[4], win_dim[4],
          win_dim[4] - 0.09*(win_dim[4] - win_dim[3]),
          win_dim[4] - 0.09*(win_dim[4] - win_dim[3]))
polygon(x_vec, y_vec, col = "grey95", border = NA)
text(x = mean(c(win_dim[1], win_dim[2])), y = (win_dim[4] - 0.09/2*(win_dim[4] - win_dim[3])), main)

# Add axes and box
lines(x_vec[1:2], rep((win_dim[4] - 0.09*(win_dim[4] - win_dim[3])),2), col = 1)
box()
axis(1, padj = 0.3)
y_axis = axis(2, labels = FALSE, tick = FALSE)
y_axis = y_axis[y_axis < (win_dim[4] - 0.09*(win_dim[4] - win_dim[3]))]
axis(2, padj = -0.2, at = y_axis)

# Add trajectory
lines(position, type = "l", col = color, pch = 16)

# Start and end points
points(c(0,position[steps+1,1]), c(0,position[steps+1,2]), cex = pt.cex, col = pt_col, pch = pt_pch)

# Legend
leg_pos = c(min(position[,1]), max(position[,2]))
legend(leg_pos[1], leg_pos[2], c("Start","End"), 
       col = pt_col, pch = pt_pch, pt.cex = pt.cex, bty = "n")

}, htmlfile = "RW3D.html")
```

```{r a, message=FALSE}
#Map Problem
library(maps)
library(ggmap)
library(rvest)

big10 = read_html("http://www.bigten.org/library/stats/fb-confsked.html#standings")
big10 %>%
  html_nodes(".b1gfbstats:nth-child(9) td:nth-child(1) , .b1gfbstats:nth-child(6) td:nth-child(1)") %>%
  html_text() -> uni_name
uni_name = paste(uni_name, "University")
uni_coord = data.frame(geocode(uni_name))
big10 %>%
  html_nodes("td:nth-child(7)") %>%
  html_text() -> uni_wp
uni_coord$wp = 100*as.numeric(uni_wp[1:length(uni_name)])
uni_coord$conf = rep(c('East Division', 'West Division'), each = length(uni_name)/2)
```
```{r, results="hide"}
uni_coord
names(uni_coord)[names(uni_coord) == 'conf'] = 'Division'
library(mapproj)
states = map_data('state')
conf_states = subset(states, region %in% c('south dakota', 'nebraska','kansas', 'minnesota', 'iowa', 'missouri', 'wisconsin', 'illinois', 'indiana', 'michigan', 'ohio', 'west virginia', 'pennsylvania', 'maryland', 'new jersey'))
```
```{r}
conf_map = ggplot(data = conf_states) + geom_polygon(aes(x = long, y = lat, group = group), fill = 'light gray', color = 'black') + coord_fixed(1.3) + geom_point(data = uni_coord, aes(lon, lat, col = Division, size = wp)) + scale_size(name = 'Win rate [%]') + xlab('Longitude') + ylab('Latitude') + ggtitle('Big 10 Conference - as of 2017-10-10')
conf_map
```
```{r eval=FALSE}
#Stock Problem
library(quantmod)
library(rvest)
sp500 = read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
sp500 %>%
  html_nodes(".text") %>%
  html_text() -> ticker_sp500
sp500_symbol = ticker_sp500[(1:499)*2+1]
sp500_symbol[sp500_symbol == 'BRK.B'] = 'BRK-B'
sp500_symbol[sp500_symbol == 'BF.B'] = 'BF-B'

today = Sys.Date()
three_years_ago = seq(today, length = 2, by = '-3 year')[2]
getSymbols(sp500_symbol, from = three_years_ago, to = today)
sp500_symbol

num_tick = length(sp500_symbol)
combos = combn(sp500_symbol, 2)
exps = rep(NA, length(sp500_symbol))
vars = rep(NA, length(sp500_symbol))
for (i in 1:dim(combos)[2]){
  Ra = na.omit(ClCl(get(combos[1,i])))
  Rn = na.omit(ClCl(get(combos[2,i])))
  
  sigma = cov(cbind(Ra, Rn))
  mu = c(mean(Ra), mean(Rn))
  
  omega_star = (sigma[2, 2] - sigma[1, 2])/(sigma[1, 1] + sigma[2, 2] - 2*sigma[1, 2])
  
  exps[i] = omega_star*mu[1] + (1 - omega_star)*mu[2]
  vars[i] = omega_star^2*sigma[1,1] + (1-omega_star)^2*sigma[2,2] + 2*omega_star*(1-omega_star)*sigma[1,2]
}

exps = exps[!is.na(exps)]
vars = vars[!is.na(vars)]
sds = sds[!is.na(sds)]
min_sds = sds>min(sds[!is.na(sds)])
min_sds = min_sds[!is.na(min_sds)]
min_sds = min_sds[!is.na(min_sds)]

stock_data = data.frame(exps, sds, min_sds)

ggplot(stock_data, aes(x=sds[!is.na(sds)], y=exps[!is.na(exps)])) + geom_point(alpha = 0.1, aes(col=min_sds)) + xlab('Investment Daily Risk') + ylab('Investment Daily Expected Rerturns') + annotate('point', x = min(sds), y = exps[!min_sds], col = 'red')
```